package com.bayport.service;



import com.bayport.entity.Owner;

import com.bayport.entity.Reminder;

import com.bayport.entity.ReminderType;

import com.bayport.repository.OwnerRepository;

import com.bayport.repository.ReminderRepository;

import lombok.extern.slf4j.Slf4j;

import org.springframework.beans.factory.annotation.Autowired;

import org.springframework.boot.context.event.ApplicationReadyEvent;

import org.springframework.context.event.EventListener;

import org.springframework.scheduling.annotation.Scheduled;

import org.springframework.stereotype.Service;



import java.time.LocalDate;

import java.time.LocalDateTime;

import java.util.ArrayList;

import java.util.HashMap;

import java.util.List;

import java.util.Map;



@Slf4j

@Service

public class ReminderScheduler {



    @Autowired

    ReminderRepository reminderRepo;



    @Autowired

    OwnerRepository ownerRepo;



    @Autowired

    EmailService emailService;



    /** Run once after the app starts so due vaccine reminders are not missed until 9 AM. */

    @EventListener(ApplicationReadyEvent.class)

    public void onApplicationReady() {

        log.info("Running startup reminder dispatch…");

        sendDueReminders();

    }



    /** Every hour on the hour — catches due/overdue pet reminders (including auto-generated vaccine reminders). */

    @Scheduled(cron = "0 0 * * * *")

    public void sendDueRemindersHourly() {

        sendDueReminders();

    }



    /** Daily at 9 AM as a backup pass. */

    @Scheduled(cron = "0 0 9 * * *")

    public void sendDueRemindersDaily() {

        sendDueReminders();

    }



    public Map<String, Object> sendDueReminders() {

        LocalDate today = LocalDate.now();

        log.info("Checking pet reminders due on or before {}", today);



        Map<String, Object> result = new HashMap<>();

        result.put("mailConfigured", emailService.isConfigured());

        result.put("emailProvider", emailService.describeProvider());

        result.put("resendSandbox", emailService.isResendSandbox());

        if (emailService.isResendSandbox()) {

            result.put("resendSandboxNote", emailService.resendSandboxNote());

        }

        result.put("checkedAt", LocalDateTime.now().toString());



        List<Reminder> due = reminderRepo.findBySentFalseAndDateLessThanEqualAndType(today, ReminderType.PET);

        result.put("dueCount", due.size());



        if (due.isEmpty()) {

            log.debug("No unsent pet reminders due for {}", today);

            result.put("sentCount", 0);

            result.put("failedCount", 0);

            result.put("skippedCount", 0);

            result.put("failures", List.of());

            result.put("message", "No due reminders to send.");

            return result;

        }

        log.info("Found {} unsent pet reminder(s) due on or before {}", due.size(), today);



        if (!emailService.isConfigured()) {

            log.warn(

                    "Email is not configured — {} reminder(s) were not sent. "

                            + "Set RESEND_API_KEY (cloud) or SPRING_MAIL_USERNAME + SPRING_MAIL_PASSWORD (local).",

                    due.size());

            result.put("sentCount", 0);

            result.put("failedCount", 0);

            result.put("skippedCount", due.size());

            result.put("failures", List.of());

            result.put("message",

                    "Email is not configured. Set RESEND_API_KEY on Render or SMTP credentials locally, then restart.");

            return result;

        }



        int sentCount = 0;

        int failedCount = 0;

        int skippedCount = 0;

        List<Map<String, Object>> failures = new ArrayList<>();



        for (Reminder r : due) {

            try {

                if (r.getOwnerId() == null) {

                    log.warn("Reminder {} has no ownerId. Skipping.", r.getId());

                    skippedCount++;

                    continue;

                }

                Owner owner = ownerRepo.findById(r.getOwnerId()).orElse(null);

                if (owner == null) {

                    log.warn("Reminder {} has invalid ownerId: {}. Skipping.", r.getId(), r.getOwnerId());

                    skippedCount++;

                    continue;

                }



                String to = owner.getEmail();

                if (to == null || to.trim().isEmpty()) {

                    log.warn("Reminder {} for owner {} has no email address. Skipping.", r.getId(), owner.getFullName());

                    skippedCount++;

                    continue;

                }



                String subject = r.isAutoGenerated()

                        ? "Vaccination Reminder - Bayport Veterinary Clinic"

                        : "Pet Reminder - Bayport Veterinary Clinic";



                String message = r.getMessage();

                if (message == null || message.trim().isEmpty()) {

                    message = r.isAutoGenerated()

                            ? "This is a reminder about an upcoming vaccination for your pet. Please contact the clinic to schedule."

                            : "This is a reminder from Bayport Veterinary Clinic regarding your pet.";

                }



                emailService.send(to.trim(), subject, message);



                r.setSent(true);

                r.setSentAt(LocalDateTime.now());

                r.setTargetEmail(to.trim());

                reminderRepo.save(r);

                sentCount++;

                log.info("Reminder email sent to {} (reminder ID: {}, auto={})", to, r.getId(), r.isAutoGenerated());



            } catch (Exception e) {

                failedCount++;

                String ownerName = null;

                String ownerEmail = null;

                try {

                    if (r.getOwnerId() != null) {

                        Owner owner = ownerRepo.findById(r.getOwnerId()).orElse(null);

                        if (owner != null) {

                            ownerName = owner.getFullName();

                            ownerEmail = owner.getEmail();

                        }

                    }

                } catch (Exception ignored) {

                    // keep failure entry with best-effort context

                }

                String friendly = friendlySendError(e.getMessage());

                failures.add(failureEntry(r.getId(), ownerName, ownerEmail, friendly));

                log.error("Failed to send reminder ID {}: {}", r.getId(), e.getMessage(), e);

            }

        }



        log.info("Reminder dispatch finished. Sent: {}, Failed: {}, Skipped: {}", sentCount, failedCount, skippedCount);

        result.put("sentCount", sentCount);

        result.put("failedCount", failedCount);

        result.put("skippedCount", skippedCount);

        result.put("failures", failures);

        result.put("message", buildSummaryMessage(sentCount, failedCount, skippedCount, failures));

        return result;

    }



    private static Map<String, Object> failureEntry(Long reminderId, String ownerName, String email, String reason) {

        Map<String, Object> row = new HashMap<>();

        row.put("reminderId", reminderId);

        if (ownerName != null) {

            row.put("ownerName", ownerName);

        }

        if (email != null && !email.isBlank()) {

            row.put("email", email.trim());

        }

        row.put("reason", reason == null || reason.isBlank() ? "Unknown error" : reason);

        return row;

    }



    private static String friendlySendError(String raw) {

        if (raw == null || raw.isBlank()) {

            return "Email delivery failed.";

        }

        String lower = raw.toLowerCase();

        if (lower.contains("only send") && lower.contains("your own email")) {

            return "Resend test mode: onboarding@resend.dev can only send to your Resend account email. "

                    + "Verify your clinic domain at resend.com/domains and set RESEND_FROM on Render.";

        }

        if (lower.contains("validation") && lower.contains("email")) {

            return "Invalid recipient email address. Check the owner's email in Pet profiles.";

        }

        if (lower.contains("resend failed")) {

            return raw.length() > 280 ? raw.substring(0, 280) + "…" : raw;

        }

        return raw.length() > 280 ? raw.substring(0, 280) + "…" : raw;

    }



    private static String buildSummaryMessage(int sent, int failed, int skipped, List<Map<String, Object>> failures) {

        StringBuilder sb = new StringBuilder();

        sb.append(String.format("Sent %d, failed %d, skipped %d.", sent, failed, skipped));

        if (!failures.isEmpty()) {

            Map<String, Object> first = failures.get(0);

            Object reason = first.get("reason");

            if (reason != null && !reason.toString().isBlank()) {

                sb.append(" ").append(reason);

            }

        }

        return sb.toString();

    }

}
