package com.bayport.service;

import com.bayport.entity.Pet;
import com.bayport.entity.Procedure;
import com.bayport.entity.Reminder;
import com.bayport.entity.ReminderType;
import com.bayport.repository.ProcedureRepository;
import com.bayport.repository.ReminderRepository;
import org.springframework.stereotype.Service;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

@Service
public class VaccineReminderService {

    private final ReminderRepository reminderRepository;
    private final ProcedureRepository procedureRepository;

    public VaccineReminderService(ReminderRepository reminderRepository, ProcedureRepository procedureRepository) {
        this.reminderRepository = reminderRepository;
        this.procedureRepository = procedureRepository;
    }

    public void syncPetVaccineReminders(Pet pet) {
        if (pet == null || pet.getId() == null || pet.getOwnerId() == null) {
            return;
        }

        reminderRepository.deleteByPetIdAndAutoGeneratedTrue(pet.getId());

        List<Procedure> procedures = procedureRepository.findByPet_Id(pet.getId())
                .stream()
                .filter(p -> p.getPerformedAt() != null)
                .sorted(Comparator.comparing(Procedure::getPerformedAt))
                .toList();

        if (procedures.isEmpty()) {
            return;
        }

        Map<String, Reminder> deduped = new LinkedHashMap<>();
        for (Procedure procedure : procedures) {
            NextReminder next = computeNextReminder(pet, procedure);
            if (next == null || next.date == null || !next.date.isAfter(LocalDate.now())) {
                continue;
            }
            Reminder reminder = buildReminder(pet, next);
            deduped.put(next.date + "|" + next.title, reminder);
        }

        if (!deduped.isEmpty()) {
            reminderRepository.saveAll(new ArrayList<>(deduped.values()));
        }
    }

    private Reminder buildReminder(Pet pet, NextReminder next) {
        String ownerName = pet.getOwner() != null && !pet.getOwner().isBlank() ? pet.getOwner() : "Pet Owner";
        String petName = pet.getName() != null && !pet.getName().isBlank() ? pet.getName() : "your pet";
        String message = String.format(
                "Subject: %s%n%nHello %s,%n%nThis is an automated vaccination reminder for %s.%n%n" +
                        "Due on: %s%nNext vaccine: %s%n%nPlease schedule your clinic visit on or before the due date.%n%n" +
                        "Bayport Veterinary Clinic",
                next.title,
                ownerName,
                petName,
                next.date,
                next.vaccine
        );

        Reminder reminder = new Reminder();
        reminder.setPetId(pet.getId());
        reminder.setOwnerId(pet.getOwnerId());
        reminder.setType(ReminderType.PET);
        reminder.setDate(next.date);
        reminder.setMessage(message);
        reminder.setSent(false);
        reminder.setSentAt(null);
        reminder.setAutoGenerated(true);
        return reminder;
    }

    private NextReminder computeNextReminder(Pet pet, Procedure procedure) {
        String text = normalize((procedure.getName() + " " + procedure.getCategory() + " " + procedure.getNotes()));
        if (!isVaccineOrDeworm(text)) {
            return null;
        }

        boolean isDog = isDog(pet.getSpecies());
        boolean isCat = isCat(pet.getSpecies());
        LocalDate performedAt = procedure.getPerformedAt();

        if (text.contains("deworm")) {
            if (pet.getAge() != null && pet.getAge() > 1) {
                return null;
            }
            return new NextReminder(
                    "Deworming Follow-up Reminder",
                    "Deworming",
                    performedAt.plusWeeks(2)
            );
        }

        if (containsAny(text, "rabies", "anti rabies", "anti-rabies")) {
            return new NextReminder(
                    "Anti-Rabies Booster Reminder",
                    "Anti-Rabies booster",
                    performedAt.plusYears(1)
            );
        }

        if (isDog && containsAny(text, "5 in 1", "5-in-1", "dhppi")) {
            return buildSeriesReminder("5-in-1", performedAt, extractDose(text), 4);
        }

        if (isCat && containsAny(text, "3 in 1", "3-in-1", "fvrcp")) {
            return buildSeriesReminder("3-in-1", performedAt, extractDose(text), 4);
        }

        return null;
    }

    private NextReminder buildSeriesReminder(String vaccineName, LocalDate performedAt, int dose, int maxPediatricDose) {
        if (dose == 1) {
            return new NextReminder(vaccineName + " Reminder", "2nd " + vaccineName, performedAt.plusWeeks(3));
        }
        if (dose == 2) {
            return new NextReminder(vaccineName + " Reminder", "3rd " + vaccineName, performedAt.plusWeeks(3));
        }
        if (dose == 3) {
            return new NextReminder(vaccineName + " Reminder", "4th " + vaccineName, performedAt.plusWeeks(3));
        }
        if (dose >= maxPediatricDose || dose == 0) {
            return new NextReminder(vaccineName + " Booster Reminder", vaccineName + " booster", performedAt.plusYears(1));
        }
        return null;
    }

    private boolean isVaccineOrDeworm(String text) {
        return containsAny(text, "vaccine", "vaccination", "rabies", "dhppi", "fvrcp", "5-in-1", "3-in-1", "deworm");
    }

    private boolean isDog(String species) {
        String value = normalize(species);
        return containsAny(value, "canine", "dog");
    }

    private boolean isCat(String species) {
        String value = normalize(species);
        return containsAny(value, "feline", "cat");
    }

    private int extractDose(String text) {
        if (containsAny(text, "1st", "first")) return 1;
        if (containsAny(text, "2nd", "second")) return 2;
        if (containsAny(text, "3rd", "third")) return 3;
        if (containsAny(text, "4th", "fourth")) return 4;
        if (containsAny(text, "booster")) return 5;
        return 0;
    }

    private String normalize(String value) {
        return value == null ? "" : value.toLowerCase(Locale.ROOT);
    }

    private boolean containsAny(String value, String... keywords) {
        String normalized = normalize(value);
        for (String keyword : keywords) {
            if (normalized.contains(normalize(keyword))) {
                return true;
            }
        }
        return false;
    }

    private static class NextReminder {
        final String title;
        final String vaccine;
        final LocalDate date;

        NextReminder(String title, String vaccine, LocalDate date) {
            this.title = title;
            this.vaccine = vaccine;
            this.date = date;
        }
    }
}
